dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5  # State management için
  hive: ^2.2.3  # Yerel depolama
  hive_flutter: ^1.1.0
  firebase_core: ^2.15.0  # Firebase temel
  firebase_auth: ^4.7.2  # Kimlik doğrulama
  cloud_firestore: ^4.8.4  # Veritabanı
  http: ^1.1.0  # API istekleri
  pdf: ^3.10.4  # PDF oluşturma
  path_provider: ^2.1.0  # Dosya işlemleri
  shared_preferences: ^2.2.0
  flutter_dotenv: ^5.1.0  # Çevre değişkenleri
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  hive_generator: ^2.0.0
  build_runner: ^2.4.6